/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as MeusEstudosRouteImport } from './routes/meus-estudos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as EstudoIdRouteImport } from './routes/estudo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusEstudosRoute = MeusEstudosRouteImport.update({
  id: '/meus-estudos',
  path: '/meus-estudos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudoIdRoute = EstudoIdRouteImport.update({
  id: '/estudo/$id',
  path: '/estudo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historico': typeof HistoricoRoute
  '/meus-estudos': typeof MeusEstudosRoute
  '/painel': typeof PainelRoute
  '/estudo/$id': typeof EstudoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historico': typeof HistoricoRoute
  '/meus-estudos': typeof MeusEstudosRoute
  '/painel': typeof PainelRoute
  '/estudo/$id': typeof EstudoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historico': typeof HistoricoRoute
  '/meus-estudos': typeof MeusEstudosRoute
  '/painel': typeof PainelRoute
  '/estudo/$id': typeof EstudoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/historico' | '/meus-estudos' | '/painel' | '/estudo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/historico' | '/meus-estudos' | '/painel' | '/estudo/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/historico'
    | '/meus-estudos'
    | '/painel'
    | '/estudo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoricoRoute: typeof HistoricoRoute
  MeusEstudosRoute: typeof MeusEstudosRoute
  PainelRoute: typeof PainelRoute
  EstudoIdRoute: typeof EstudoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-estudos': {
      id: '/meus-estudos'
      path: '/meus-estudos'
      fullPath: '/meus-estudos'
      preLoaderRoute: typeof MeusEstudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudo/$id': {
      id: '/estudo/$id'
      path: '/estudo/$id'
      fullPath: '/estudo/$id'
      preLoaderRoute: typeof EstudoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoricoRoute: HistoricoRoute,
  MeusEstudosRoute: MeusEstudosRoute,
  PainelRoute: PainelRoute,
  EstudoIdRoute: EstudoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
